const MOVEMENT_DETAILS = {
    "ac": {
        "title": "Arts & Crafts",
        "dates": "c. 1880–1920",
        "theme": "ac",
        "quote": "Truth to Materials",
        "description": "The Arts and Crafts movement was a passionate rebellion against the soul-crushing machinery of the Industrial Revolution. It wasn\'t just about pretty wallpaper; it was a moral crusade for the return of craftsmanship, honest materials, and the dignity of the worker. Led by William Morris, it sought to reunite art and labor, creating simple, beautiful objects that brought joy to both the maker and the user. It was the original \'farm-to-table\' of the design world.",
        "philosophy": "**Truth to Materials.** The movement believed that wood should look like wood, and metal like metal. It rejected the deceptive veneers and over-decoration of the Victorian era. The philosophy was grounded in **Socialist Idealism**, aiming to improve the lives of ordinary people by surrounding them with well-made, meaningful objects. It championed the **Unity of Art**, erasing the distinction between \'fine\' arts (painting, sculpture) and \'applied\' arts (furniture, textiles).",
        "impact": "Arts and Crafts laid the ethical foundation for Modernism. Its emphasis on **functionality** and **simplicity** directly influenced the Bauhaus and Scandinavian design. While it ultimately failed to make good design affordable for the masses (hand-crafting is expensive!), its spirit lives on in the DIY movement, sustainable design, and anyone who appreciates a well-joined oak table.",
        "sociopolitical_context": "The Arts and Crafts movement emerged in Britain during the late 19th century as a direct visceral reaction to the **industrialization of society**. The Victorian era was characterized by rapid technological advancement, but also by horrific working conditions, urban squalor, and a flood of cheap, shoddy mass-produced goods. Thinkers like **John Ruskin** and **William Morris** looked at the smoking factories of Manchester and saw not progress, but the degradation of the human spirit. They believed that the division of labor—where a worker spent 12 hours a day making just one part of a pin—reduced men to mere machines. \n\nThis was a time of immense social inequality. The wealthy elite filled their homes with ostentatious, machine-made ornaments that mimicked historical styles, while the poor lived in destitution. The movement was deeply intertwined with **early Socialist thought**. Morris himself was a committed socialist who believed that bad design was a symptom of a sick, capitalist society. He argued that you couldn\'t have beautiful art without a beautiful society. Thus, the movement wasn\'t just aesthetic; it was political. It advocated for a return to the **medieval guild system**, where workers were respected artisans who took pride in their whole creation. \n\nHowever, the movement faced a critical paradox: by rejecting the machine, their products became incredibly time-consuming and expensive to produce. The \'art for the people\' became art for the rich elite who could afford handcrafted tapestries. Despite this economic failure, its sociopolitical critique of industrial capitalism resonated globally. It sparked similar movements in America (Stickley), Austria (Wiener Werkstätte), and Germany (Deutscher Werkbund), shifting the conversation from \'how do we make more stuff?\' to \'how should we live?\' It established the idea that **labor, art, and society are inextricably linked**, a concept that remains relevant in today\'s discussions about automation and the gig economy.",
        "key_features": ["Rejection of the Machine", "Honest Construction", "Nature-inspired Patterns"]
    },
    "an": {
        "title": "Art Nouveau",
        "dates": "c. 1890–1910",
        "theme": "an",
        "quote": "The First International Style",
        "description": "Art Nouveau (\'New Art\') was a dramatic, short-lived explosion of organic energy that swept across Europe at the turn of the century. It was the first truly international style, rejecting historical mimicry for a new language of sinuous curves, whiplash lines, and biological rhythms. It was total design: architects like Victor Horta didn\'t just design the building; they designed the door handles, the carpets, and the forks, creating immersive environments of unified beauty.",
        "philosophy": "**The Synthesis of Life and Art.** Art Nouveau sought to break down the barriers between fine art and everyday objects. It drew heavy inspiration from **Darwinian biology** and the discovery of microscopic life, translating cellular structures and plant forms into architecture. It was purely aesthetic but deeply psychological, using **asymmetry** and **dynamic motion** to evoke emotion and vitality.",
        "impact": "While it burned out quickly, Art Nouveau liberated design from the shackles of the past. It paved the way for Modernism by proving that a new, contemporary style was possible. Its influence is seen in the psychedelic art of the 1960s and the organic curves of contemporary biomorphism (like Ross Lovegrove or Zaha Hadid). It taught us that structure itself could be decoration.",
        "sociopolitical_context": "Art Nouveau blossomed during the **Belle Époque**, a period of relative peace and prosperity in Europe before the devastation of World War I. It was the aesthetic of a confident, bourgeois society looking to define a modern identity distinct from the stuffy conservatism of the 19th century. Culturally, it was fueled by a fascination with the natural sciences. **Darwin’s *On the Origin of Species*** (1859) and the drawings of **Ernst Haeckel** revealed a world of microscopic beauty—radiolarians, jellyfish, cell structures—that designers eagerly translated into iron and glass. \n\nPolitically, it was often associated with **progressive liberalism**. In Belgium and France, it was the style of the new money—industrialists and intellectuals who wanted to distinguish themselves from the old aristocracy. It was also a reaction against the academic art establishment. However, it was also a product of **colonialism**. The influx of Japanese art (Japonisme) into Europe fundamentally changed Western composition, introducing asymmetry and flat graphical planes. \n\nThe movement was also deeply connected to the **Changing Role of Women**. The \'New Woman\' of the turn of the century—independent, educated, and active—was often motif in Art Nouveau posters (like Mucha\'s), though often in a highly sexualized, femme fatale manner. Ultimately, Art Nouveau was a victim of its own elitism and the changing tides of history. As tensions rose leading up to WWI, its decadence and expense began to feel out of touch. The machine age demanded something harder, faster, and more rational. Yet, for a brief moment, it offered a dream of a world where everything, from a metro entrance to a necklace, was a living, breathing work of art.",
        "key_features": ["Organic Abstraction", "Whiplash Curves", "Unity of Art"]
    },
    "ae": {
        "title": "Aesthetic Movement",
        "dates": "c. 1860–1900",
        "theme": "an",
        "quote": "Art for Art's Sake",
        "description": "The Aesthetic Movement was the rebellious teenager of the Victorian era. Its motto, \'Art for Art\'s Sake\', declared that art didn\'t need to teach a moral lesson or tell a story; it just needed to be beautiful. Think peacock feathers, blue-and-white china, and Oscar Wilde holding a lily. It was an escape from the grime of industrial London into a world of refined sensuality and cultivated taste.",
        "philosophy": "**Art for Art\'s Sake.** A reaction against the utiltarianism and moralizing art of the time. It valued **sensual pleasure** over social function. It emphasized **mood**, **color harmony**, and the **cult of the beautiful**. It was less about how things worked, and more about how they made you *feel*.",
        "impact": "It elevated the status of decorative arts and set the stage for the concept of \'lifestyle\' design. It introduced the idea that one\'s home was a reflection of one\'s artistic sensibility. It also heavily popularized **Japanese aesthetics** in the West, a thread that would influence Minimalism a century later.",
        "sociopolitical_context": "The Aesthetic Movement arose in the mid-19th century Britain as a localized but intense reaction against the **utilitarianism of the Industrial Age** and the **moral strictness of the Victorian era**. At the time, art was expected to serve a purpose: to uphold moral values, tell historical stories, or reinforce religious dogma. The Aesthetes, led by figures like **James McNeill Whistler** and **Oscar Wilde**, famously rejected this. They argued that art should have no purpose other than to exist and be beautiful. \n\nThis was a radical, almost subversive idea in a society obsessed with productivity and piety. It was a form of **cultural rebellion**. The movement mocked the stuffy, clutter-filled interiors of the middle class, proposing instead \'House Beautiful\' interiors filled with ebonized wood, sunflower motifs, and subtle color palettes. It was also deeply tied to the **opening of Japan** in 1853. The flood of Japanese woodblock prints and ceramics into Europe stunned Western artists. They adopted the Japanese concept of *Ma* (space) and asymmetrical balance, which became a core tenet of Aestheticism. \n\nThe movement was constantly satirized by the conservative press (most famously in *Punch* magazine and Gilbert and Sullivan\'s *Patience*) as effeminate and pretentious. This tension highlighted a growing **crisis of masculinity** and anxiety about the \'softening\' of British society. While often dismissed as superficial, the Aesthetic Movement was actually a profound critique of a society that valued money and toil over beauty and experience. It asserted the right of the individual to craft their own identity through their environment, a concept that is the very basis of modern consumer culture.",
        "key_features": ["Ebonized Wood", "Peacock Feathers", "Japanese Influence"]
    },
    "sm": {
        "title": "Scientific Management",
        "dates": "c. 1910s–1920s",
        "theme": "sm",
        "quote": "Efficiency is Beauty",
        "description": "Also known as Taylorism, this wasn\'t an \'art\' movement but a quest for efficiency that accidentally created a design aesthetic. Frederick Winslow Taylor used stopwatches to time every motion of a factory worker. This logic was applied to the home (Christine Frederick) and the kitchen (The Frankfurt Kitchen), treating domestic life as a factory process to be optimized. The result? The modern fitted kitchen.",
        "philosophy": "**Efficiency is Beauty.** The elimination of waste—wasted time, wasted motion, wasted space. Form was dictated by **ergonomics** and **process flow**. It celebrated **standardization**, hygiene, and the \'one best way\' to do any task.",
        "impact": "It gave us the **work triangle** in the kitchen, standard countertop heights, and the very concept of the \'fitted\' kitchen. It shifted design from \'decoration\' to \'problem-solving\'. While its obsession with efficiency can feel cold, it laid the groundwork for modern ergonomics and UX design.",
        "sociopolitical_context": "Scientific Management rose to prominence in the early 20th century, reaching its peak around World War I. It was born from the mind of **Frederick Winslow Taylor**, who sought to solve the inefficiencies of the industrial shop floor. But it quickly mutated into a social philosophy. In a world rapidly urbanizing and mechanizing, \'efficiency\' became a god. The **Progressive Era** in America believed that science and logic could solve any social ill, from poverty to corruption. \n\nFor design, the impact was profound. **Christine Frederick** applied Taylor\'s factory principles to the home in her book *Household Engineering*. She argued that the housewife was a manager, and the kitchen her factory. This aligned with the **Suffragette movement**—if women could finish their housework faster through efficient design, they would have time for education and political participation. In Europe, specifically post-WWI Germany, this took on a desperate urgency. The housing crisis required millions of units to be built cheaply and quickly. The **Frankfurt Kitchen** (1926) by Margarete Schütte-Lihotzky was the ultimate manifestation: a tiny, hyper-efficient lab for cooking based on motion studies. \n\nSociopolitically, this was the era of the **expert**. It was a top-down approach where architects and engineers believed they knew how people *should* live better than the people themselves. It prioritized the collective, the standard, and the hygienic over the individual or the cozy. While it liberated women from hours of drudgery, it also isolated them in a specific \'work zone\'. It turned the home into a machine for living, a concept that would become the central dogma of Modernism.",
        "key_features": ["Frankfurt Kitchen", "Motion Studies", "Standardization"]
    },
    "bh": {
        "title": "The Bauhaus",
        "dates": "1919–1933",
        "theme": "bh",
        "quote": "Form Follows Function",
        "description": "Dimensions, functionality, and geometric purity. The Bauhaus was the most influential design school in history. Founded by Walter Gropius in Weimar, Germany, it aimed to bridge the gap between art and industry. It stripped away the \'bourgeois\' ornamentation of the past, favoring steel, glass, and primary colors. It taught that a lamp or a chair could be mass-produced and still have soul.",
        "philosophy": "**Form Follows Function.** Radical simplification. The belief in the **Gesamtkunstwerk** (total work of art) under the banner of modern industry. It utilized **basic geometric shapes** (circle, square, triangle) and **primary colors**. It sought a \'universal language\' of design that transcended nationality and class.",
        "impact": "Immeasurable. The Bauhaus defined the look of the 20th century. It gave us the glass curtain wall skyscraper, the tubular steel chair, and modern typography. Its teaching methods (the Vorkurs or foundation course) are still used in design schools worldwide. It proved that good design could be democratic.",
        "sociopolitical_context": "The Bauhaus was born from the ashes of **World War I**. The German Empire had collapsed, replaced by the fragile, chaotic, but creatively explosive **Weimar Republic**. The war had destroyed not just buildings, but faith in the old order—the Kaisers, the ornamentation, the nationalism. Gropius founder the Bauhaus in 1919 with a utopian vision: to build a new society through design. It was deeply political, often associated with **left-wing radicalism**. The school operated under the belief that better architecture and objects could create better citizens. \n\nThe school\'s existence was a constant struggle against the rising tide of **Nazism**. The right-wing nationalists hated the Bauhaus. They saw its rejection of German Gothic script for sans-serif type, and its flat roofs (which they called \'oriental\'), as \'Un-German\' and \'Cultural Bolshevism\'. Because of this pressure, the school moved from conservative Weimar to industrial Dessau, and finally to Berlin. \n\nThe **Great Depression** further emphasized the school\'s shift towards functionality and affordability/standardization under Hannes Meyer. They needed to design for the proletariat, not the elite. In 1933, the Gestapo raided and closed the school. Ironically, this persecution ensured its global dominance. Major figures like Gropius, Breuer, and Mies van der Rohe fled to America (Harvard, IIT), transplanting the Bauhaus ethos into the heart of **Corporate America**. Thus, a style born of socialist utopianism became the preferred aesthetic of capitalism—the glass corporate headquarters.",
        "key_features": ["Geometric Purity", "Tubular Steel", "Workshop Learning"]
    },
    "modernism": {
        "title": "Modernism",
        "dates": "c. 1920–1960",
        "theme": "modernism", // Custom color in CSS
        "quote": "Less is More",
        "description": "The big umbrella. Modernism wasn\'t just a style; it was a worldview. It believed in progress, rationality, and technology. It rejected the cluttered past for a clean, bright, electric future. From the white villas of Le Corbusier to the sleek radios of Braun, it promised a better life through rational design. It was the visual language of the 20th century.",
        "philosophy": "**Less is More.** (Mies van der Rohe). A rejection of history and ornament. A faith in **technology** and **mass production**. A preference for **abstraction**, transparency, and honest materials (concrete, steel, glass). It aimed for objectively \'good\' design.",
        "impact": "It created the modern world. Our cities, our airports, our phones—all rooted in Modernist principles. It established the standard that function should dictate form. While later criticized as sterile or authoritarian, its clarity and utility remain the gold standard for interface and product design.",
        "sociopolitical_context": "Modernism was the visual manifestation of the **20th Century\'s faith in progress**. It spans the interwar period, WWII, and the post-war boom, united by a belief that the past was obsolete and the future belonged to science, reason, and democracy (or sometimes, totalitarianism). \n\nIn the 1920s, Modernism was revolutionary socialism—housing for the workers, sunlight, hygiene. It was a disinfectant against the dark, disease-ridden tenements of the 19th century. **Le Corbusier** famously said, \'Architecture or Revolution\', implying that if we didn\'t solve living conditions through design, the masses would revolt. \n\nPost-WWII, Modernism transformed. In America, it became the style of the **Pax Americana**. The clean, international style represented corporate efficiency and global capitalism. It was the look of the \'Free World\'—transparent, rational, and orderly—in contrast to the perceived secrecy of the Iron Curtain (though the Soviets had their own brute Modernism). \n\nIt also coincided with the **Rise of the Middle Class**. Modernism promised that good design wasn\'t just for the rich; with plastic and plywood, high-style furniture could be mass-produced for the suburban home. However, its universality was also its weakness. By the 1960s, the **Counterculture** began to view Modernism not as a liberator, but as the face of \'The Man\'—sterile corporate towers and inhuman housing projects that bred alienation. But for forty years, it was the unquestioned optimism of the machine age.",
        "key_features": ["Rejection of Ornament", "Focus on Volume", "Industrial Materials"]
    },
    "ad": {
        "title": "Art Deco & Streamlining",
        "dates": "c. 1925–1939",
        "theme": "ad",
        "quote": "The Style of Speed",
        "description": "If Bauhaus was the nutritious vegetable of design, Art Deco was the candy. It was glamour, jazz, and speed. Born in Paris but perfected in New York, it celebrated the machine age not with logic, but with drama. Then came Streamlining: obsessed with aerodynamics, designers smoothed out the corners of everything—from trains to pencil sharpeners—to make them look like they were moving 100mph while standing still.",
        "philosophy": "**The Style of Speed.** A celebration of **modernity** and **luxury**. It used **geometric ornamentation** (sunbursts, zigzags) and **exotic materials** (ivory, chrome, lacquer). Streamlining added the distinct **teardrop shape** and parallel \'speed lines\' to symbolize the frictionless future.",
        "impact": "It invented the profession of **Industrial Design**. Raymond Loewy and Henry Dreyfuss showed that good design sells. It shaped the American landscape (diners, cinemas, gas stations) and gave us the classic imagery of \'The Future\'—rocket ships and ray guns.",
        "sociopolitical_context": "Art Deco roared into existence during the **Roaring Twenties**, a time of post-war euphoria, jazz, and economic bubbles. It embodied the consumerist dream. Unlike the socialist Bauhaus, Deco didn\'t want to save the world; it wanted to make it fabulous. It was the style of the flapper, the skyscraper, and the ocean liner. \n\nBut its second phase, **Streamlining**, tells a darker story. It emerged during the **Great Depression** (1930s). The economy had collapsed. People were desperate. Manufacturers needed a way to get people to buy things they didn\'t really need. Enter the Industrial Designer (Loewy, Bel Geddes, Dreyfuss). They took existing mechanisms, encased them in a sleek, aerodynamic shell, and sold them as \'new\'. This was the birth of **planned obsolescence**. \n\nStreamlining was a psychological balm for a bruised nation. In a time of chaos and poverty, these friction-free, rounded forms promised a smooth, gleaming future. The **1939 New York World\'s Fair** (\'The World of Tomorrow\') was its cathedral. It was also deeply tied to the **rise of transport**. The airplane and the Zephyr train captivated the public imagination. By applying these aerodynamic shapes to stationary objects like toasters and staplers, designers were selling the *idea* of progress. It was the ultimate triumph of styling over function, perfectly suited for the capitalist recovery of America.",
        "key_features": ["Teardrop Shapes", "Speed Lines", "Chrome & Bakelite"]
    },
    "midcentury": {
        "title": "Mid-Century Modern",
        "dates": "c. 1945–1965",
        "theme": "midcentury",
        "quote": "Good Design is Good Business",
        "description": "The Golden Age of American Design. After WWII, designers took the hard rationalism of Modernism and softened it. They used wartime technologies—molded plywood (Eames), fiberglass, aluminum—to create furniture that was organic, comfortable, and affordable. It was optimistic, colorful design for the booming suburbs, serving the new American Dream.",
        "philosophy": "**Good Design is Good Business.** (Thomas Watson Jr.). A marriage of **mass production** and **organic form**. It prioritized **flexibility** (modular systems), **open living**, and a seamless connection between indoors and outdoors. It was democratic design for the nuclear family.",
        "impact": "It redefined the home. The open-plan living room, the sliding glass door, the lounge chair—all MCM innovations. It remains the most popular vintage style today because it hit the sweet spot between modern sleekness and domestic warmth.",
        "sociopolitical_context": "Mid-Century Modern (MCM) is the aesthetic of the **Post-War Boom**. The US emerged from WWII as the world\'s superpower, with its manufacturing base intact and a booming economy. millions of GIs returned home, creating a massive housing shortage. The **GI Bill** and suburban developments like Levittown created a sudden, massive market for furniture. These young families didn\'t want the heavy, dark antiques of their parents. They wanted something new, affordable, and easy to clean (no servants!). MCM fit the bill perfectly. \n\nTechnologically, it was a **sword-to-ploughshares** movement. The Eameses perfected molding plywood for leg splints during the war; afterwards, they used the same machines to make chairs. Saarinen used fiberglass developed for radar domes to make womb chairs. Chemical companies like **DuPont** and **Dow** pushed new plastics, promising \'Better Living Through Chemistry\'. \n\nCulturally, it represented the **Atomic Age** optimism. The \'Starburst\' clocks and kidney-shaped tables reflected a fascination with both the cosmic and the microscopic. It was also a tool of **Cold War Soft Power**. The US State Department sent exhibitions of modern design (like \'modern living\') to Europe and Moscow to prove that Capitalism provided a better standard of living than Communism. The kitchen debate between Nixon and Khrushchev took place in a model GE kitchen. MCM was arguably the most effective propaganda America ever produced.",
        "key_features": ["Molded Plywood", "Organic Curves", "Open Floor Plans"]
    },
    "biomorphism": {
        "title": "Biomorphism",
        "dates": "c. 1935–1955",
        "theme": "biomorphism",
        "quote": "Flowing Natural Forms",
        "description": "Not a strict school, but a pervasive trend. As the machine age matured, designers looked back to nature. They adopted the shapes of biology—kidneys, amoebas, boomerangs, and bones. Influenced by surrealist art (Miró, Arp) and new plastic capabilities, it injected a sense of fluidity and life into the hard geometry of Modernism.",
        "philosophy": "**Flowing Natural Forms.** Inspiration from **biology** and **surrealism**. A rejection of the straight line in favor of the curve. It sought to make the artificial feel organic and ergonomic.",
        "impact": "It gave us the iconic \'kidney pool\', the Noguchi table, and the Tupperware container. It softened the hard edges of International Style architecture and introduced a playful, sculptural element to industrial design that paved the way for the ergonomics of the 1990s.",
        "sociopolitical_context": "Biomorphism emerged in the 1930s and 40s as a psychological counter-balance to the rigid grid of the International Style. If the grid represented logic and the machine, the blob represented **the unconscious and the organic**. It was heavily influenced by **Surrealism** in art (Jean Arp, Joan Miró, Salvador Dalí), which explored the dream state and hidden desires. \n\nSociopolitically, it gained traction during and after **World War II**. The war had shown the destructive power of the machine. People craved something softer, more human, and safer. The **discovery of the organic world** through improved photography and microscopy also played a role—images of cells and amoebas became popular motifs. \n\nMaterially, it was driven by the **Plastic Revolution**. New thermoplastics could be molded into complex, glorious curves that wood and metal simply couldn\'t achieve (cheaply). In the 1950s, biomorphism became the look of the \'friendly atom\' and the futuristic home. But it also carried a subtle subversiveness—a chaotic, uncontrollable organic energy bubbling up inside the conformist, grey-flannel-suit society of the Eisenhower era.",
        "key_features": ["Kidney Shapes", "Amoeba Forms", "Soft Edges"]
    },
    "ulm": {
        "title": "Ulm School",
        "dates": "1953–1968",
        "theme": "ulm",
        "quote": "Design is a System",
        "description": "The spiritual successor to the Bauhaus. Located in Ulm, Germany, this school sterilized design. It removed the \'art\' and replaced it with \'science\'. It focused on semiotics, systems, and strict methodology. It partnered with Braun to create the \'black box\' aesthetic—matte, minimal, and unobtrusive. It is the grandfather of the Apple aesthetic.",
        "philosophy": "**Design is a System.** Extreme **Rationalism**. A rejection of styling and fashion. Design should be **objective**, intellectually rigorous, and socially responsible. It pioneered **system design**—products that stack and interlock.",
        "impact": "It created the **Braun style** (Dieter Rams) which defined the look of high-tech electronics for 50 years. It influenced the corporate identity of Lufthansa and the signage of metro systems. It professionalized design, ensuring it was seen as a technical discipline like engineering, not an artistic one.",
        "sociopolitical_context": "The Hochschule für Gestaltung Ulm (Ulm School of Design) was founded in 1953 by Inge Aicher-Scholl, Otl Aicher, and Max Bill. Its origins are deeply tragic and political: it was dedicated to the memory of Hans and Sophie Scholl, members of the **White Rose resistance** executed by the Nazis. \n\nAs such, Ulm was founded on a bedrock of **Anti-Fascist democracy**. The founders believed that the aestheticization of politics (the rallies, the flags, the emotions) had led to Nazism. Therefore, design had to be stripped of all emotion, nostalgia, and manipulation. It had to be purely rational, objective, and truthful. This was **Design as Moral Hygiene**. \n\nThe school operated during the influential years of the **Wirtschaftswunder** (German Economic Miracle). As German industry rebuilt, it needed a new identity—one that was precise, high-quality, and distinctly NOT nationalist. Ulm provided this: the \'German Engineering\' aesthetic. \n\nHowever, the school was famously torn by internal conflict. Max Bill wanted a continuation of the Bauhaus artist-craftsman. The younger faculty (Tomas Maldonado) wanted \'scientific operationalism\'—using sociology, semiotics, and computer theory. Science won. The school closed in 1968 amidst funding cuts and political tensions, but its students spread its \'cool\' logic into the boardrooms of corporate Europe, defining the rational, Helvetica-driven look of late 20th-century globalization.",
        "key_features": ["Modular Systems", "Matte Finishes", "Extreme Rationalism"]
    },
    "italian_rationalism": {
        "title": "Italian Rationalism",
        "dates": "c. 1960–1980",
        "theme": "sm", // Reusing rationalism color
        "quote": "Tradition and Modernity",
        "description": "While Germany was making cold, matte-black boxes, Italy was having a renaissance. Italian Rationalism (and the Bel Design era) balanced modern manufacturing with centuries of cultural history. Designers like Bellini, Castiglioni, and Zanuso used new plastics to create objects that were sculptural, witty, and beautiful, but still deeply functional. It made Italy the global capital of style.",
        "philosophy": "**Tradition and Modernity.** A refusal to separate technology from **humanism**. Objects should have **personality**. The use of **bold curves** and **glossy plastics**. It treated the factory like a craftsman\'s workshop.",
        "impact": "It established the \'Made in Italy\' brand. It gave us the Valentine typewriter, the Arco lamp, and the Brionvega radio. It showed that modern products could be desirable objects of desire, not just tools. It laid the groundwork for the \'emotional design\' of the future.",
        "sociopolitical_context": "Post-war Italy was a country of contradictions: rapid industrialization in the North (Milan/Turin) vs. agrarian poverty in the South; a strong Communist party vs. the Vatican. Design became the bridge. The **Italian Economic Miracle** of the late 50s and 60s needed products. But unlike the Germans, Italians refused to let go of history. \n\nItalian architects (and they were almost all architects, not \'industrial designers\') were steeped in the Renaissance and Classical history. They viewed the plastic chair not just as a unit of production, but as a continuation of the sculpture tradition. This was the era of the **Maestro**—Castiglioni, Sottsass, Zanuso—working directly with enlightened industrialists like **Adriano Olivetti**. Olivetti was a key figure: a socialist capitalist who believed factories should be community centers and that workers deserved beauty. \n\nThis unique collaboration allowed for risk-taking that American corporations wouldn\'t touch. \n\nHowever, by the late 1960s, the political climate darkened (**The Years of Lead**). Strikes, terrorism, and student riots questioned the validity of consumerism. Radical Design groups (Archizoom, Superstudio) began to attack the very Rationalism that built the miracle, arguing that \'Good Design\' was just a mask for consumer enslavement. This tension between the beautiful object and the critical theory is the heart of Italian design.",
        "key_features": ["Elegant Proportions", "Bold Plastics", "Cultural Depth"]
    },
    "minimalism": {
        "title": "Minimalism",
        "dates": "c. 1960–Present",
        "theme": "minimalism",
        "quote": "Less, but Better",
        "description": "The art of subtraction. Emerging from the art world in the 60s and refined by designers like Jasper Morrison and Naoto Fukasawa, Minimalism is the final destination of Modernism. It isn\'t just about \'simple\'; it\'s about \'essential\'. It removes the noise to amplify the signal. In a world of information overload, it offers silence.",
        "philosophy": "**Less, but Better.** (Dieter Rams again). **Super Normal.** The object should disappear into the background. Focus on **purity of form**, **neutral colors**, and **perfect proportions**. It is anti-expressive and anti-ego.",
        "impact": "It is the dominant aesthetic of the digital age (think Apple, Muji, Google\'s material design). It shaped the smartphone, the gallery space, and the high-end apartment. It suggests that clarity of space leads to clarity of mind.",
        "sociopolitical_context": "Minimalism began as a high-art movement in 1960s New York (Judd, Stella) as a rejection of the emotional excess of Abstract Expressionism. But as a design lifestyle, it gained true power in the late 20th and early 21st centuries. \n\nSociopolitically, modern Minimalism is often a response to **Consumerist Overload**. In a late-capitalist world drowning in cheap goods, advertising, and digital noise, Minimalism is a form of luxury. It implies that you are rich enough to have *less*. You don\'t need to hoard; you can afford to replace. \n\nIt also has deep roots in **Japanese Zen Buddhism**, particularly through brands like Muji. This philosophy equates emptiness with potentiality. In the 1990s and 2000s, figures like Jasper Morrison and Naoto Fukasawa coined \'Super Normal\'—design that is so humble it recedes. \n\nHowever, there is a critique: \'Minimalism is the aesthetic of the end of history\'. It is the perfect style for global neoliberalism because it is frictionless. A minimalist lobby looks the same in Tokyo, Berlin, or New York. It strips away local culture and history in favor of a smooth, featureless surface. It is the design of the \'airport lounge\' world. Despite this, its promise of peace and order remains incredibly seductive in our chaotic, notification-driven lives.",
        "key_features": ["Simplicity", "Neutral Colors", "Clean Lines"]
    },
    "wedge": {
        "title": "Wedge Era",
        "dates": "c. 1968–1985",
        "theme": "wedge",
        "quote": "The Future is Sharp",
        "description": "The Car Design revolution. For a brief, sharp moment, cars stopped looking like curvy animals and started looking like spaceships and doorstops. Designers like Gandini and Giugiaro drew single, aggressive lines from the nose to the tail. It was low, fast, and intensely futuristic. The Lamborghini Countach is the holy grail.",
        "philosophy": "**The Future is Sharp.** Rejection of the \'feminine\' curves of the 1950s/60s. **Aerodynamic implication** (even if not reality). A focus on **planar geometry**, **trapezoids**, and breaking the mold of the traditional \'three-box\' car.",
        "impact": "It defined the supercar. The DeLorean, the Lotus Esprit, the Lancia Stratos. It influenced the \'folded paper\' look of 1980s electronics and continues to inspire cyberpunk aesthetics today (like the Cybertruck).",
        "sociopolitical_context": "The Wedge Era was born in **1968**, a year of global revolution. Student riots in Paris, protests in America, labor unrest in Italy. The polite, soft curves of the post-war era suddenly felt old-fashioned. The Wedge was aggressive. It looked dangerous. It was a visual disruption. \n\nCentered in Turin, Italy, led by **Bertone** and **Italdesign**, it was also a technical flex. The move from front-engine to mid-engine layouts allowed designers to drop the hoodline drastically. But it was largely a **formatting of the future**. This was the era of the Space Race ending and the Sci-Fi dystopia beginning (*Blade Runner*, *Alien*). The Wedge car looked like it belonged on Mars. \n\nIt was also, undeniably, an expression of **hyper-masculinity**. These cars were difficult to drive, impossible to see out of, and uncomfortable. They didn\'t care. They existed to shock and to perform. The era ended in the mid-80s due to safety regulations (pedestrian safety laws hate sharp noses) and a shift back towards organic \'jelly bean\' aerodynamics (like the Ford Taurus). But for 15 years, the Wedge was the ultimate symbol of speed and daring.",
        "key_features": ["Sharp Angles", "Flat Planes", "Aggressive Stance"]
    },
    "pm": {
        "title": "Post-Modernism",
        "dates": "c. 1980–1995",
        "theme": "pm",
        "quote": "Form Follows Fun",
        "description": "The party after the funeral of Modernism. By the 1970s, people were bored of glass boxes and black radios. Post-Modernism said: \'Let\'s have fun\'. It looted the history books, mixing Greek columns with neon lights and cheap plastic. It was ironic, colorful, confusing, and contradictory. It broke all the rules just to see what would happen.",
        "philosophy": "**Form Follows Fun.** (or Fiction). A rejection of \'universal truth\'. **Double-coding**: designs that appeal to the public with humor and to the elite with irony. A celebration of **ornament**, **metaphor**, and **pastiche**.",
        "impact": "It shattered the authority of the \'Good Design\' priesthood. It brought color and emotion back into the home (Alessi kettles, Michael Graves architecture). While often derided today as tacky, it liberated designers to be authors and artists, not just problem solvers.",
        "sociopolitical_context": "Post-Modernism (PoMo) is the design language of the **Neoliberal Turn** (Reagan/Thatcher era). The grand narratives of the 20th century—Socialism, Progress, Science—were collapsing. Philosophers like Lyotard and Baudrillard argued that reality was being replaced by signs and simulacra. \n\nPoMo reflected this fractured reality. It abandoned the Modernist dream of a utopia for everyone. Instead, it embraced **individualism and consumerism**. If Modernism was about production, Post-Modernism was about *communication*. A teapot wasn\'t just for boiling water; it was a conversation piece, a status symbol, a joke. \n\nIt was also a reaction to the failure of Modernist urban planning (like the demolition of Pruitt-Igoe). Architects realized that people didn\'t want concrete machines; they wanted memory, decoration, and familiarity. So they pasted styrofoam classical arches onto strip malls. \n\nCulturally, it matched the **MTV generation**: fast cuts, bright colors, surface over depth. It was the first movement to truly embrace the \'fake\'—laminates that looked like bacteria, plastic that looked like marble. It was cynical, yet exuberantly creative, perfectly mirroring the boom-and-bust energy of the 1980s.",
        "key_features": ["Humor & Kitsch", "Bold Colors", "Historical Pastiche"]
    },
    "mem": {
        "title": "Memphis Group",
        "dates": "1981–1987",
        "theme": "mem",
        "quote": "A New International Style",
        "description": "A specific, explosive sub-sect of Post-Modernism. Founded in Milan by Ettore Sottsass, the Memphis Group was a \'shotgun wedding between Bauhaus and Fisher-Price\'. They created furniture that was intentionally difficult to use, covered in wild bacteria patterns, and made of cheap laminate. It was a direct \'middle finger\' to the good taste of the design establishment.",
        "philosophy": "**A New International Style.** Break the rules. Mix high and low culture. Use **clashing colors**, **asymmetry**, and **totemic shapes**. Design is **poetry**, not service. It was designed for the media, not for the market.",
        "impact": "Karl Lagerfeld bought the whole collection. David Bowie collected it. It was a media sensation that defined the \'80s aesthetic (think *Saved by the Bell*). While commercially a flop (too weird for real homes), it completely freed designers from the tyranny of \'good taste\'.",
        "sociopolitical_context": "Memphis was a **Rock \'n\' Roll** moment in design. In fact, it was named after a Bob Dylan song played on loop during their first meeting (\'Stuck Inside of Mobile with the Memphis Blues Again\'). \n\nEttore Sottsass was an established genius of Italian Rationalism (he designed the Valentine typewriter), but he was bored. He felt design had become a slave to industry and marketing. Memphis was a **revolt against the Bourgeoisie**. It celebrated the cheap, the synthetic, and the \'bad taste\' of American suburbia—plastic laminates found in cheap diners—and elevated them to high art. \n\nIt was deeply **anti-consumables**. The furniture was huge, expensive, and barely functional (you couldn\'t really sit on the chairs). It forced the user to interact with the object as a presence, not a tool. In a way, it was the final scream of the Radical Design movement of the 60s, packaged for the media age of the 80s. It dissolved quickly (by 1987), proving its point: trends are ephemeral, and permanence is a lie.",
        "key_features": ["Clashing Patterns", "Laminate materials", "Totemic shapes"]
    },
    "ht": {
        "title": "High-Tech",
        "dates": "c. 1970–1990",
        "theme": "sm",
        "quote": "The Machine Aesthetic",
        "description": "Shouldn\'t a house look like a machine? High-Tech architecture and design took the industrial elements usually hidden behind the walls—pipes, ducts, trusses—and painted them bright colors and put them on display. From the Pompidou Centre to the Dyson vacuum, it celebrates the engineering of the object. It says: \'This is how I work, and that is why I am beautiful.\'",
        "philosophy": "**The Machine Aesthetic.** Honesty of **structure** and **function**. Use of **industrial materials** (steel, glass, rubber) in domestic settings. **Prefabrication** and **flexibility**. The building/object as a flexible kit of parts.",
        "impact": "It gave us the Pompidou Centre and the Lloyds building. In product design, it led directly to **Dyson\'s** see-through bin vacuums and the rugged aesthetic of heavy-duty tools. It romanticized the engineer as the new artist.",
        "sociopolitical_context": "High-Tech emerged in the 1970s, a time of **technological optimism** amidst economic gloom. The Space Race had put men on the moon; computers were shrinking. Architects like **Richard Rogers** and **Norman Foster** believed technology could solve social problems. \n\nThe **Pompidou Centre** (1977) in Paris is the manifesto: a cultural center turned inside out, democratic, flexible, and looking like an oil refinery. It shocked the establishment. Domestically, the \'High-Tech\' book by Joan Kron (1978) encouraged people to use factory shelving and hospital trolleys in their apartments. This was a reaction to the \'fluff\' of decoration, but also a pragmatic response to urban living—industrial gear was tough and functional. \n\nIt aligns with the **Information Age**. As society moved from heavy industry to information, High-Tech buildings began to look like circuit boards or servers. It is the aesthetic of transparency—literally showing the workings of the system. In a post-Watergate world, \'transparency\' was a political virtue. \n\nUltimately, High-Tech evolved into the sleek, silver engineering of the Apple Store—technology so advanced it became invisible—but its roots are in the exposed bolts and bright yellow HVAC ducts of the 70s.",
        "key_features": ["Exposed Structure", "Industrial Materials", "Functional Aesthetics"]
    }
};
